@tool
class_name DialogueData extends Resource

# One NPC's complete dialogue — all nodes, quest relations, metadata.
# Loaded from .tres files generated by tools/dialogue_to_tres.py.
# Editable in the Godot Inspector.

@export var npc_id: String = ""
@export var display_name: String = ""
@export var default_node: String = "node_000"
@export var world_id: String = ""
@export var quest_relations: Array[String] = []
@export var nodes: Array[DialogueNode] = []
