class_name WorldTriggers extends Resource

## Baked output of a TMX's ObjectGroup(s). One .tres per world scene,
## generated by tools/tmx_triggers_to_tres.py. TriggerSpawner loads the
## .tres at runtime and instances each TriggerData as a Godot node.
##
## Path convention: res://assets/map_data/triggers/{SceneBaseName}.tres
## Example: "World_00_Blacksmith" → "res://assets/map_data/triggers/World_00_Blacksmith.tres"
##
## The source_tmx field is recorded so TriggerSpawner can do a debug-build
## staleness check (is the TMX newer than the .tres?).

## Source TMX file path (relative to project root), recorded for staleness checks.
@export var source_tmx: String = ""

@export var triggers: Array[TriggerData] = []
