using Godot;
using System.Collections.Generic;

namespace AdventureLandPrototype;

/// <summary>
/// Loads tile data from CSV files generated by the TMX converter
/// and populates TileMapLayer nodes at runtime.
/// </summary>
public partial class MapLoader : Node2D
{
    [Export] public bool AutoLoad = true;

    private const int TileSourceId = 0; // Atlas source ID in the TileSet

    public override void _Ready()
    {
        if (AutoLoad)
        {
            LoadAllLayers();
        }
    }

    private void LoadAllLayers()
    {
        // Find all TileMapLayer children and load their corresponding CSV data
        foreach (var child in GetChildren())
        {
            if (child is TileMapLayer layer)
            {
                string csvPath = $"res://assets/map_data/{layer.Name}.csv";
                LoadLayerFromCsv(layer, csvPath);
            }
        }

        GD.Print("Map loaded successfully!");
    }

    private void LoadLayerFromCsv(TileMapLayer layer, string csvPath)
    {
        if (!FileAccess.FileExists(csvPath))
        {
            GD.PrintErr($"Map data not found: {csvPath}");
            return;
        }

        var file = FileAccess.Open(csvPath, FileAccess.ModeFlags.Read);
        int tileCount = 0;

        while (!file.EofReached())
        {
            string line = file.GetLine().StripEdges();
            if (string.IsNullOrEmpty(line)) continue;

            string[] parts = line.Split(',');
            if (parts.Length < 4) continue;

            int x = int.Parse(parts[0]);
            int y = int.Parse(parts[1]);
            int atlasX = int.Parse(parts[2]);
            int atlasY = int.Parse(parts[3]);

            layer.SetCell(new Vector2I(x, y), TileSourceId, new Vector2I(atlasX, atlasY));
            tileCount++;
        }

        file.Close();
        GD.Print($"  Loaded {layer.Name}: {tileCount} tiles");
    }
}
