using Godot;
using System.Collections.Generic;

namespace AdventureLandPrototype;

/// <summary>
/// Loads tile data from CSV files generated by the TMX converter
/// and populates TileMapLayer nodes at runtime.
///
/// Critical: Godot 4 TileSetAtlasSource requires tiles to be explicitly
/// created via CreateTile() before SetCell() will render them. Otherwise
/// SetCell silently does nothing. We track created atlas coordinates
/// across all layers so we only create each tile once.
/// </summary>
public partial class MapLoader : Node2D
{
    [Export] public bool AutoLoad = true;

    private const int TileSourceId = 0;

    // Tracks atlas coords we've already created (shared across all layers
    // since they all reference the same TileSet)
    private readonly HashSet<Vector2I> _createdTiles = new();

    public override void _Ready()
    {
        if (AutoLoad)
        {
            LoadAllLayers();
        }
    }

    private void LoadAllLayers()
    {
        int totalTiles = 0;
        foreach (var child in GetChildren())
        {
            if (child is TileMapLayer layer)
            {
                string csvPath = $"res://assets/map_data/{layer.Name}.csv";
                totalTiles += LoadLayerFromCsv(layer, csvPath);
            }
        }

        GD.Print($"Map loaded: {totalTiles} tiles across {_createdTiles.Count} unique atlas positions");
    }

    private int LoadLayerFromCsv(TileMapLayer layer, string csvPath)
    {
        if (!FileAccess.FileExists(csvPath))
        {
            GD.PrintErr($"Map data not found: {csvPath}");
            return 0;
        }

        var tileSet = layer.TileSet;
        if (tileSet == null)
        {
            GD.PrintErr($"Layer '{layer.Name}' has no TileSet");
            return 0;
        }

        var atlasSource = tileSet.GetSource(TileSourceId) as TileSetAtlasSource;
        if (atlasSource == null)
        {
            GD.PrintErr($"TileSet source {TileSourceId} is not a TileSetAtlasSource");
            return 0;
        }

        var file = FileAccess.Open(csvPath, FileAccess.ModeFlags.Read);
        int tileCount = 0;

        while (!file.EofReached())
        {
            string line = file.GetLine().StripEdges();
            if (string.IsNullOrEmpty(line)) continue;

            string[] parts = line.Split(',');
            if (parts.Length < 4) continue;

            int x = int.Parse(parts[0]);
            int y = int.Parse(parts[1]);
            int atlasX = int.Parse(parts[2]);
            int atlasY = int.Parse(parts[3]);

            var atlasCoord = new Vector2I(atlasX, atlasY);

            // Create tile in atlas if not already done
            if (!_createdTiles.Contains(atlasCoord))
            {
                if (!atlasSource.HasTile(atlasCoord))
                {
                    atlasSource.CreateTile(atlasCoord);
                }
                _createdTiles.Add(atlasCoord);
            }

            layer.SetCell(new Vector2I(x, y), TileSourceId, atlasCoord);
            tileCount++;
        }

        file.Close();
        GD.Print($"  {layer.Name}: {tileCount} tiles");
        return tileCount;
    }
}
