extends Node

# Autoload -- no class_name (collides with the autoload singleton name).
#
# Shared UI styling helpers -- one place for the project's pixel-art
# button style, dialogue/toast frame texture, and the cream/teal palette.
#
# Keep this file the single source of truth: DialogueManager,
# ItemPickupToast, TitleScreen, etc. all call into here so a retheme
# touches one helper.
#
# Register in Project -> Autoload as:
#   Path: res://scripts/ui/UiStyles.gd
#   Name: UiStyles

# ---- Texture paths (loaded lazily) ----
const _PATH_BTN_NORMAL: String = "res://assets/sprites/ui/panel_btn_normal.png"
const _PATH_BTN_HOVER: String = "res://assets/sprites/ui/panel_btn_hover.png"
const _PATH_PANEL_BG: String = "res://assets/sprites/ui/panel_bg.png"
const _PATH_FRAME_BG: String = "res://assets/sprites/ui/dialogue/frame_bg.png"
const _PATH_ARROW: String = "res://assets/sprites/ui/icon_arrow.png"
const _PATH_ARROW_UP: String = "res://assets/sprites/ui/ui_hintarrow-up-000.png"
const _PATH_ARROW_DOWN: String = "res://assets/sprites/ui/ui_hintarrow-down-000.png"
const _PATH_HEART: String = "res://assets/sprites/ui/heart_full.png"
const _PATH_SWORD: String = "res://assets/sprites/ui/icon_sword.png"
const _PATH_BAG: String = "res://assets/sprites/ui/icon_bag.png"
const _PATH_SHIELD: String = "res://assets/sprites/ui/inventory/stat_2.png"
const _PATH_BOOT_STAT: String = "res://assets/sprites/ui/inventory/stat_3.png"
const _PATH_GEM: String = "res://assets/sprites/ui/gem.png"
const _PATH_SPACE: String = "res://assets/sprites/ui/icon_space.png"
const _PATH_MENU_FONT: String = "res://assets/fonts/spritefont_menu.fnt"

# Lazy texture cache. _ensure_<name>() called on first access.
var _tex_btn_normal: Texture2D
var _tex_btn_hover: Texture2D
var _tex_panel_bg: Texture2D
var _tex_frame_bg: Texture2D
var _tex_arrow: Texture2D
var _tex_arrow_up: Texture2D
var _tex_arrow_down: Texture2D
var _tex_heart: Texture2D
var _tex_sword: Texture2D
var _tex_bag: Texture2D
var _tex_shield: Texture2D
var _tex_boot_stat: Texture2D
var _tex_gem: Texture2D
var _tex_space: Texture2D
var _font_menu: Font


# Plain pixel-art button frame (16x16) -- clean cream/teal, no ornament,
# designed for clean nine-slicing at any size.
func btn_normal() -> Texture2D:
	if _tex_btn_normal == null:
		_tex_btn_normal = load(_PATH_BTN_NORMAL) as Texture2D
	return _tex_btn_normal


func btn_hover() -> Texture2D:
	if _tex_btn_hover == null:
		_tex_btn_hover = load(_PATH_BTN_HOVER) as Texture2D
	return _tex_btn_hover


# Plain pixel-art panel frame (24x24) -- replaces the ornate curly
# frame_bg for non-dialogue UI surfaces (toasts, title menus).
# Nine-slices cleanly to any size without distortion.
func panel_bg() -> Texture2D:
	if _tex_panel_bg == null:
		_tex_panel_bg = load(_PATH_PANEL_BG) as Texture2D
	return _tex_panel_bg


# The original ornate dialogue frame -- keep for the in-game dialogue
# box where the cameo + name strip are designed around it. Don't use
# for resizable panels.
func frame_bg() -> Texture2D:
	if _tex_frame_bg == null:
		_tex_frame_bg = load(_PATH_FRAME_BG) as Texture2D
	return _tex_frame_bg


func arrow() -> Texture2D:
	if _tex_arrow == null:
		_tex_arrow = load(_PATH_ARROW) as Texture2D
	return _tex_arrow


func arrow_up() -> Texture2D:
	if _tex_arrow_up == null:
		_tex_arrow_up = load(_PATH_ARROW_UP) as Texture2D
	return _tex_arrow_up


func arrow_down() -> Texture2D:
	if _tex_arrow_down == null:
		_tex_arrow_down = load(_PATH_ARROW_DOWN) as Texture2D
	return _tex_arrow_down


func heart() -> Texture2D:
	if _tex_heart == null:
		_tex_heart = load(_PATH_HEART) as Texture2D
	return _tex_heart


func sword() -> Texture2D:
	if _tex_sword == null:
		_tex_sword = load(_PATH_SWORD) as Texture2D
	return _tex_sword


func bag() -> Texture2D:
	if _tex_bag == null:
		_tex_bag = load(_PATH_BAG) as Texture2D
	return _tex_bag


# Shield icon (stat_2) -- Defense stat, used for any equippable
# clothing slot (Head/Neck/Body/Hand/Legs).
func shield() -> Texture2D:
	if _tex_shield == null:
		_tex_shield = load(_PATH_SHIELD) as Texture2D
	return _tex_shield


# Boot icon (stat_3) -- Speed stat, used for the Boot slot.
func boot_stat() -> Texture2D:
	if _tex_boot_stat == null:
		_tex_boot_stat = load(_PATH_BOOT_STAT) as Texture2D
	return _tex_boot_stat


func gem() -> Texture2D:
	if _tex_gem == null:
		_tex_gem = load(_PATH_GEM) as Texture2D
	return _tex_gem


func space() -> Texture2D:
	if _tex_space == null:
		_tex_space = load(_PATH_SPACE) as Texture2D
	return _tex_space


# SpriteFont_Menu -- the C3 bitmap font used for title-screen labels
# and any copy that isn't sitting on a panel/button background. Loaded
# from the .fnt generated by tools/gen_menu_font_fnt.py.
func menu_font() -> Font:
	if _font_menu == null:
		_font_menu = load(_PATH_MENU_FONT) as Font
	return _font_menu


# ---- Palette ----
# Locked palette: cream font (#fbffbd) on #cdb246 panel BG. Same pair
# is used by dialogue body, toast text, button labels, and any "copy on
# a panel" surface so the UI reads as one family.
const CREAM: Color = Color(0.984, 1.000, 0.741, 1.0)  # #fbffbd -- body text
const CREAM_LIT: Color = Color(1.000, 1.000, 0.850, 1.0)  # hover/active text
const CREAM_DIM: Color = Color(0.78, 0.78, 0.55, 1.0)  # pressed text
const GRAY: Color = Color(0.55, 0.55, 0.55, 1.0)  # inactive
const WHITE: Color = Color(1.00, 1.00, 1.00, 1.0)  # titles / active selection
const GOOD_GREEN: Color = Color(0.4, 1.0, 0.4, 1.0)
const BAD_RED: Color = Color(1.0, 0.4, 0.4, 1.0)


# ---- Mobile detection ----
# True when running on a touch-first platform. Decided on title screen
# via detect_mobile() and persisted; readable by any UI that needs to
# adapt to touch.
var is_mobile: bool = false

# Fires when is_mobile changes. Subscribed by autoload UI that builds
# mobile-specific elements in _ready and would otherwise stay frozen
# in its boot-time state when the user toggles mode at runtime.
# Pattern I -- the C# facade exposes this as `event Action MobileChanged`.
signal mobile_changed


# Detect once at boot. True if either:
#   * The build was exported for a mobile platform target (iOS / Android),
#     in which case OS.has_feature("mobile") is true, OR
#   * The build is the HTML5 web target running on a touch device.
# Desktop builds + the editor return false even when the host machine
# happens to expose a touch surface (e.g., Mac trackpads report
# DisplayServer.is_touchscreen_available() = true on M-series chips).
# Caller persists choice via set_mobile_override().
func detect_mobile() -> bool:
	# Real mobile build (iOS / Android export target).
	var platform_mobile: bool = OS.has_feature("mobile")

	# Web heuristic: trust the viewport size as the primary signal.
	# Mac/PC browsers report DisplayServer.is_touchscreen_available()
	# = true on M-series chips and modern Surface devices, so that
	# alone falsely enables mobile mode on desktop browsers. A small
	# viewport (< 600 px wide) is a much more reliable mobile cue --
	# desktop browser windows are virtually never that narrow, and
	# mobile portrait viewports almost always are. Combine with
	# touchscreen-available so a small desktop window doesn't
	# accidentally trip it either.
	var touch_on_web: bool = false
	if OS.has_feature("web"):
		var view: Vector2i = DisplayServer.window_get_size()
		var narrow: bool = view.x > 0 and view.x < 600
		touch_on_web = narrow and DisplayServer.is_touchscreen_available()

	is_mobile = platform_mobile or touch_on_web
	return is_mobile


# Hard-set the mobile flag. Used when SaveData has a stored preference,
# or when the user toggles the choice from settings or the Shift+M
# debug shortcut. Fires mobile_changed if the value actually changed.
func set_mobile_override(mobile: bool) -> void:
	if is_mobile == mobile:
		return
	is_mobile = mobile
	mobile_changed.emit()


# ---- Button style ----

# Apply the project's standard pixel-art button style -- frame 0 of C3's
# Btn_Action sprite for normal/pressed, frame 1 for hover/focus.
# Nine-sliced via texture_margin = 4 so it scales to any button size.
func apply_btn_action_style(btn: Button) -> void:
	const MARGIN: int = 4

	var normal := _make_btn_stylebox(btn_normal(), MARGIN)
	var hover := _make_btn_stylebox(btn_hover(), MARGIN)

	btn.add_theme_stylebox_override("normal", normal)
	btn.add_theme_stylebox_override("pressed", normal)
	btn.add_theme_stylebox_override("hover", hover)
	btn.add_theme_stylebox_override("focus", hover)
	btn.add_theme_color_override("font_color", CREAM)
	btn.add_theme_color_override("font_hover_color", CREAM_LIT)
	btn.add_theme_color_override("font_pressed_color", CREAM_DIM)


static func _make_btn_stylebox(tex: Texture2D, margin: int) -> StyleBoxTexture:
	var sb := StyleBoxTexture.new()
	sb.texture = tex
	sb.texture_margin_left = margin
	sb.texture_margin_right = margin
	sb.texture_margin_top = margin
	sb.texture_margin_bottom = margin
	sb.content_margin_left = 12
	sb.content_margin_right = 12
	sb.content_margin_top = 6
	sb.content_margin_bottom = 6
	return sb


# Build the project-standard panel stylebox using panel_bg.png (24x24).
# Patch margin = 5 captures the entire decorative border (1px outline +
# 2px teal + 1px highlight + 1px lowlight) so all four bands stay 1px
# thick when the panel stretches -- only the solid cream interior gets
# stretched.
func make_panel_stylebox(content_padding: int = 16) -> StyleBoxTexture:
	var sb := StyleBoxTexture.new()
	sb.texture = panel_bg()
	sb.texture_margin_left = 5
	sb.texture_margin_right = 5
	sb.texture_margin_top = 5
	sb.texture_margin_bottom = 5
	sb.content_margin_left = content_padding
	sb.content_margin_right = content_padding
	sb.content_margin_top = content_padding
	sb.content_margin_bottom = content_padding
	return sb


# Force the "hover" style as the default -- used to mark the
# keyboard-selected button in a row of choices, since we manage focus
# ourselves and Godot's `focus` state alone doesn't always render.
func apply_btn_action_style_highlighted(btn: Button) -> void:
	const MARGIN: int = 4
	var hover := _make_btn_stylebox(btn_hover(), MARGIN)

	btn.add_theme_stylebox_override("normal", hover)
	btn.add_theme_stylebox_override("pressed", hover)
	btn.add_theme_stylebox_override("hover", hover)
	btn.add_theme_stylebox_override("focus", hover)
	btn.add_theme_color_override("font_color", CREAM_LIT)


# Toggle a button between the highlighted (yellow border, dark teal
# interior) and idle (teal border, soft cream interior) looks.
func restyle_button(btn: Button, highlighted: bool) -> void:
	if highlighted:
		apply_btn_action_style_highlighted(btn)
	else:
		apply_btn_action_style(btn)


# ---- Action button (button + key hint) ----

# Build a panel-button with the primary label centered. Just the
# button -- call create_action_button_with_hint() if you also want the
# keyboard-hint label stacked below it. `on_pressed` is a Callable.
func create_action_button(label: String, on_pressed: Callable, highlighted: bool = false) -> Button:
	var btn := Button.new()
	btn.text = label
	btn.process_mode = Node.PROCESS_MODE_ALWAYS
	btn.focus_mode = Control.FOCUS_NONE
	btn.mouse_default_cursor_shape = Control.CURSOR_POINTING_HAND
	btn.custom_minimum_size = Vector2(96, 36)
	btn.add_theme_font_size_override("font_size", 18)
	# Belt-and-suspenders: explicit center alignment so the label sits
	# visually centered regardless of theme defaults / icon offsets.
	btn.alignment = HORIZONTAL_ALIGNMENT_CENTER
	btn.icon_alignment = HORIZONTAL_ALIGNMENT_CENTER
	if highlighted:
		apply_btn_action_style_highlighted(btn)
	else:
		apply_btn_action_style(btn)
	if on_pressed.is_valid():
		btn.pressed.connect(on_pressed)
	return btn


# Build a button + an optional keyboard-hint label stacked below it.
# Returns a Dictionary with "wrapper" (VBoxContainer) and "button"
# (Button) keys. On mobile the hint is suppressed and only the button
# is returned (still wrapped so callers don't branch on layout).
func create_action_button_with_hint(label: String, key_hint: String, on_pressed: Callable, highlighted: bool = false) -> Dictionary:
	var wrapper := VBoxContainer.new()
	wrapper.add_theme_constant_override("separation", 4)
	wrapper.size_flags_vertical = Control.SIZE_SHRINK_BEGIN

	var btn := create_action_button(label, on_pressed, highlighted)
	# Center the button inside the wrapper so the hint can be a wider
	# text label without offsetting the button's horizontal position.
	var btn_row := HBoxContainer.new()
	btn_row.alignment = BoxContainer.ALIGNMENT_CENTER
	btn_row.add_child(btn)
	wrapper.add_child(btn_row)

	if not is_mobile and not key_hint.is_empty():
		var hint := Label.new()
		hint.text = key_hint
		hint.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		hint.add_theme_font_size_override("font_size", 14)
		hint.add_theme_color_override("font_color", Color(CREAM.r, CREAM.g, CREAM.b, 0.85))
		hint.add_theme_constant_override("shadow_offset_x", 0)
		hint.add_theme_constant_override("shadow_offset_y", 0)
		wrapper.add_child(hint)

	return { "wrapper": wrapper, "button": btn }
