using Godot;
using Godot.Collections;

namespace AdventureLandPrototype;

/// <summary>
/// One NPC's complete dialogue — all nodes, quest relations, metadata.
/// Loaded from .tres files generated by tools/dialogue_to_tres.py.
/// Editable in the Godot Inspector.
/// </summary>
[GlobalClass]
public partial class DialogueData : Resource
{
    [Export] public string NpcId { get; set; } = "";
    [Export] public string DisplayName { get; set; } = "";
    [Export] public string DefaultNode { get; set; } = "node_000";
    [Export] public string WorldId { get; set; } = "";
    [Export] public Array<string> QuestRelations { get; set; } = new();
    [Export] public Array<DialogueNode> Nodes { get; set; } = new();
}
